BookStore/BookStore/Areas/Admin/Controllers/AuthorsController.cs
using BookStore.Services.Admin;
using BookStore.Web.Areas.Admin.Models.Authors;
using BookStore.Web.Infrastructure.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace BookStore.Web.Areas.Admin.Controllers
{
    public class AuthorsController : AdminController
    {
        private readonly IAdminAuthorService authorService;
        private readonly IAdminBookService bookService;

        public AuthorsController(IAdminAuthorService authorService, IAdminBookService bookService)
        {
            this.authorService = authorService;
            this.bookService = bookService;
        }

        public async Task<IActionResult> Index()
        {
            var authors = await this.authorService.GetAllAuthors().ToListAsync();

            return this.View(authors);
        }

        public IActionResult Create()
        {
            return this.View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(AuthorInputModel authorModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(authorModel);
            }

            var result = await this.authorService.CreateAsync(authorModel.FirstName, authorModel.LastName);

            if (result == false)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.AuthorNotCreated);
                return RedirectToAction(nameof(Index));
            }

            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Books(int id)
        {
            var author = await this.authorService.GetByIdAsync(id);

            if (author == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.AuthorNotFound);
                return this.RedirectToAction(nameof(Index));
            }
            var books = bookService.GetBooksByAuthorId(id);
            return this.View(books);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var author = await this.authorService
                .GetByIdAsync(id);

            if (author == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.AuthorNotFound);
                return RedirectToAction(nameof(Index));
            }

            return this.View(new AuthorInputModel
            {
                FirstName = author.FirstName,
                LastName = author.LastName
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AuthorInputModel authorModel)
        {

            if (!this.ModelState.IsValid)
            {
                return this.View(authorModel);
            }

            var result = await this.authorService.EditAsync(
                id,
                authorModel.FirstName,
                authorModel.LastName);

            if (result == false)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.AuthorNotEdited);
                return RedirectToAction(nameof(Index));
            }

            this.TempData.AddSuccessMessage(string.Format(
                WebAdminConstants.AuthorUpdated,
                authorModel.FirstName,
                authorModel.LastName));

            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Hide(int id)
        {
            var author = await this.authorService
                .GetByIdAsync(id);

            if (author == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.AuthorNotFound);
                return RedirectToAction(nameof(Index));
            }

            var result  = await this.authorService.HideAsync(id);

            if (result == false)
            {
                this.TempData.AddErrorMessage(string.Format(WebAdminConstants.AuthorIncludesBooks,
                   $"{author.FirstName} {author.LastName}"));
                return RedirectToAction(nameof(Index));
            }

            this.TempData.AddSuccessMessage(string.Format(
              WebAdminConstants.AuthorHidden,
              author.FirstName,
              author.LastName));

            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Show(int id)
        {
            var author = await this.authorService
             .GetByIdAsync(id);

            if (author == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.AuthorNotFound);
                return RedirectToAction(nameof(Index));
            }

            await this.authorService.ShowAsync(id);

            this.TempData.AddSuccessMessage(string.Format(
              WebAdminConstants.AuthorShowed,
              author.FirstName,
              author.LastName));

            return this.RedirectToAction(nameof(Index));
        }
    }
}

BookStore/BookStore/Areas/Admin/Controllers/ReviewsController.cs
using BookStore.Services.Admin;
using BookStore.Web.Infrastructure.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace BookStore.Web.Areas.Admin.Controllers
{
    public class ReviewsController : AdminController
    {
        private readonly IAdminReviewService reviewService;

        public ReviewsController(IAdminReviewService reviewService)
        {
            this.reviewService = reviewService;
        }
        public async Task<IActionResult> Index()
        {
            var reviews = await this.reviewService.GetAllReviews().ToListAsync();

            return this.View(reviews);
        }

        public async Task<IActionResult> Delete(int id, int bookId)
        {
            var review = await this.reviewService
              .GetByIdAsync(id);

            var result = await this.reviewService
                .RemoveAsync(id);

            if (result == false)
            {
                return RedirectToAction(nameof(Index));
            }

            this.TempData.AddSuccessMessage(string.Format(
               WebAdminConstants.ReviewDeleted));

            return this.RedirectToAction(nameof(Web.Controllers.BooksController.Details), "Books", new { id = review.BookId });
        }
    }
}

BookStore/BookStore/Areas/Admin/Controllers/UsersController.cs
using BookStore.Domain;
using BookStore.Services.Admin;
using BookStore.Web.Areas.Admin.Models.Users;
using BookStore.Web.Infrastructure.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Web.Areas.Admin.Controllers
{
    public class UsersController : AdminController
    {
        private readonly IAdminUserService adminUserService;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<BookStoreUser> userManager;

        public UsersController(
            IAdminUserService adminUserService,
            RoleManager<IdentityRole> roleManager,
            UserManager<BookStoreUser> userManager)
        {
            this.adminUserService = adminUserService;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = await this.adminUserService.GetAllUsers().ToListAsync();

            var roles = await this.roleManager
                .Roles
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name 
                })
                .ToListAsync();

            return View(new AdminUserListingViewModel
            {
                Users = users,
                Roles = roles
            });
        }
        public async Task<IActionResult> Roles(string id)
        {

            var user = await this.userManager.FindByIdAsync(id);

            if (user == null)
            {
                this.ModelState.AddModelError(string.Empty, WebAdminConstants.UserInvalidIdentityDetails);
            }
            var roles = await this.userManager.GetRolesAsync(user);

            return this.View(new UserRolesViewModel
            {
                User = user,
                UserRoles = roles
                .Select(role => new SelectListItem
                {
                    Text = role,
                    Value = role
                })
                .ToList(),
                Roles = await roleManager.Roles
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name
                })
                .ToListAsync()
        }); 
        }
        [HttpPost]
        public async Task<IActionResult> AddToRole(UserRoleInputModel model)
        {
            var roleExists = await this.roleManager.RoleExistsAsync(model.Role);
            var user = await this.userManager.FindByIdAsync(model.UserId);

            if (!roleExists || user == null)
            {
                this.ModelState.AddModelError(string.Empty, WebAdminConstants.UserInvalidIdentityDetails);
            }

            if (!this.ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            await this.userManager.AddToRoleAsync(user, model.Role);

            this.TempData.AddSuccessMessage(string.Format(
                WebAdminConstants.UserAddedToRole,
                user.UserName,
                model.Role));

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromRole(UserRoleInputModel model)
        {
            var roleExists = await this.roleManager.RoleExistsAsync(model.Role);
            var user = await this.userManager.FindByIdAsync(model.UserId);

            if (!roleExists || user == null)
            {
                this.ModelState.AddModelError(string.Empty, WebAdminConstants.UserInvalidIdentityDetails);
            }

            if (!this.ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            await this.userManager.RemoveFromRoleAsync(user, model.Role);

            this.TempData.AddSuccessMessage(string.Format(
                WebAdminConstants.UserRemovedFromRole,
                user.UserName,
                model.Role));

            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore/BookStore/Controllers/BooksController.cs
using BookStore.Controllers;
using BookStore.Services;
using BookStore.Web.Infrastructure.Extensions;
using BookStore.Web.Models.Reviews;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BookStore.Web.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly IBookService bookService;
        private readonly IReviewService reviewService;
        private readonly ICategoryService categoryService;

        public BooksController(IBookService bookService,IReviewService reviewService,ICategoryService categoryService)
        {
            this.bookService = bookService;
            this.reviewService = reviewService;
            this.categoryService = categoryService;
        }
        public async Task<IActionResult> Details(int id)
        {
            var book = await this.bookService.GetByIdAsync(id);

            if (book == null)
            {
                this.TempData.AddErrorMessage(WebConstants.BookNotFound);
                return this.RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var reviews = await reviewService.GetReviewsByBook(id).ToListAsync();
            book.Reviews = reviews;

            return this.View(book);
        }

        [HttpPost]
        public async Task<IActionResult> Review(ReviewInputModel reviewModel)
        {
            var creatorId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var result  = await this.reviewService.CreateAsync(reviewModel.BookId, reviewModel.Text, creatorId);

            if (result == false)
            {
                this.TempData.AddErrorMessage(WebConstants.ReviewNotCreated);
                return RedirectToAction(nameof(Details));
            }

            return this.RedirectToAction(nameof(Details), new { id = reviewModel.BookId });
        }
    }
}

BookStore/BookStore/Views/Shared/_CategoriesPartial.cshtml
@model IndexViewModel
<div class="mt-5">
    <aside class="category-filters margin-bottom-20">
        <h4>Книги</h4>
        <ul class="cateogry-filters-list">
            @foreach (var category in Model.Categories)
            {
                <li> <a asp-controller="Home" asp-action="Index" asp-route-CategoryId="@category.Id" class="text-info font-weight-bold">@category.Name</a></li>
            }
        </ul>
    </aside>
</div>

BookStore/BookStore/Views/Shared/_CategoriesSearchPartial.cshtml
@model SearchViewModel
<div class="mt-4">
    <aside class="category-filters margin-bottom-20">
        <h4>Книги</h4>
        <ul class="cateogry-filters-list">
            @foreach (var category in Model.Categories)
            {
                <li> <a asp-controller="Home" asp-action="Index" asp-route-CategoryId="@category.Id" class="text-info font-weight-bold">@category.Name</a></li>
            }
        </ul>
    </aside>
</div>

BookStore/BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/reset-css.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/reset-css.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container-fluid">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary rounded">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarColor01">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index"> Начало</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole(WebConstants.AdministratorRole))
                        {
                            <li class="nav-item dropdown">
                                <div class="dropdown show">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="dropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Админ
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a asp-area="Admin" asp-controller="Users" asp-action="Index" class="dropdown-item "> Потребители</a>
                                        <a asp-area="Admin" asp-controller="Categories" asp-action="Index" class="dropdown-item "> Категории</a>
                                        <a asp-area="Admin" asp-controller="Publishers" asp-action="Index" class="dropdown-item "> Издателства</a>
                                        <a asp-area="Admin" asp-controller="Authors" asp-action="Index" class="dropdown-item "> Автори</a>
                                        <a asp-area="Admin" asp-controller="Books" asp-action="Index" class="dropdown-item "> Книги</a>
                                        <a asp-area="Admin" asp-controller="Reviews" asp-action="Index" class="dropdown-item "> Ревюта</a>
                                    </div>
                                </div>
                            </li>
                        }
                        <partial name="~/Views/Shared/_LoginPartial.cshtml" />
                    </ul>
                </div>
            </nav>
        </header>
        <main>
           
            @if (TempData.ContainsKey(WebConstants.TempDataSuccessMessageKey))
            {
                <div class="alert alert-success alert-dismissible w-50" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    @Html.Raw(TempData[WebConstants.TempDataSuccessMessageKey])
                </div>
            }
            @if (TempData.ContainsKey(WebConstants.TempDataErrorMessageKey))
            {
                <div class="alert alert-danger alert-dismissible w-50" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    @Html.Raw(TempData[WebConstants.TempDataErrorMessageKey])
                </div>
            }
                        
            @RenderBody()
        </main>
        <footer class="w-75 mt-3 mx-auto rounded w-100">
            <div class="bg-primary rounded">
                <div class="text-white p-3 text-center font-weight-bold">
                    &copy; CopyRight BookStore 2019. Всички права запазени.
                </div>
            </div>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

BookStore/BookStore/Views/Shared/_MenuCategoriesSearchPartial.cshtml
@model SearchViewModel
<div class="mt-4">
    <aside class="category-filters margin-bottom-20">
        @*<div class="category-filters-section hidden-xs hidden-sm">*@
        <h4>Книги</h4>
        <ul class="cateogry-filters-list">
            @foreach (var category in Model.Categories)
            {
                <li> <a asp-controller="Home" asp-action="Index" asp-route-CategoryId="@category.Id" class="text-info">@category.Name</a></li>
            }
        </ul>
        @*</div>*@
    </aside>
</div>