BookStore/BookStore/Areas/Admin/Models/Books/BookCategoriesViewModel.cs
using BookStore.Services.Admin.Models.Books;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace BookStore.Web.Areas.Admin.Models.Books
{
    public class BookCategoriesViewModel
    {
        public AdminBookListingServiceModel Book { get; set; }

        public IEnumerable<SelectListItem> BookCategories { get; set; } 

        public IEnumerable<SelectListItem> AllCategories { get; set; } 
    }
}

BookStore/BookStore/Areas/Admin/Models/Books/BookInputModel.cs
using BookStore.Domain.Constants;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookStore.Web.Areas.Admin.Models.Books
{
    public class BookInputModel
    {

        [Required(ErrorMessage = (WebAdminConstants.Error))]
        [MaxLength(DataConstants.BookTitleMaxLength)]
        [Display(Name = "Заглавие")]
        public string Title { get; set; }

        [Required(ErrorMessage = (WebAdminConstants.Error))]
        [Display(Name = "Автор")]
        public int AuthorId { get; set; }

        [Required(ErrorMessage = (WebAdminConstants.Error))]
        [Display(Name = "Издателство")]
        public int PublisherId { get; set; }

        [Required(ErrorMessage = (WebAdminConstants.Error))]
        [MaxLength(DataConstants.BookLanguageMaxLength)]
        [Display(Name = "Език")]
        public string Language { get; set; }

        [Required(ErrorMessage = (WebAdminConstants.Error))]
        [MaxLength(DataConstants.BookDescriptionMaxLength)]
        [Display(Name = "Описание")]
        public string Description { get; set; }

        [Required(ErrorMessage = (WebAdminConstants.Error))]
        [Display(Name = "Снимка")]
        public IFormFile Image { get; set; }

        [Required(ErrorMessage = (WebAdminConstants.Error))]
        [Range(0.1, double.MaxValue, ErrorMessage = "Цената трябва да бъде положително число.")]
        [Display(Name = "Цена")]
        public decimal Price { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Дата на създаване")]
        public DateTime? CreatedOn { get; set; }

        public IEnumerable<SelectListItem> Authors { get; set; }
        public IEnumerable<SelectListItem> Publishers { get; set; }
    }
}

BookStore/BookStore/Models/Books/BookDetailsViewModel.cs
using BookStore.Domain;
using BookStore.Services.Mapping;
using BookStore.Services.Models.Reviews;
using System.Collections.Generic;

namespace BookStore.Web.Models.Books
{
    public class BookDetailsViewModel : IMapFrom<Book>
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string AuthorFullName { get; set; }

        public string PublisherName { get; set; }

        public string Language { get; set; }

        public string Description { get; set; }

        public string Image { get; set; }

        public decimal Price { get; set; }

        public IEnumerable<ReviewListingServiceModel> Reviews { get; set; }
    }
}

BookStore/BookStore/Areas/Admin/Controllers/BooksController.cs
using BookStore.Services;
using BookStore.Services.Admin;
using BookStore.Services.Admin.Models.Books;
using BookStore.Web.Areas.Admin.Models.Books;
using BookStore.Web.Areas.Admin.Models.Categories;
using BookStore.Web.Infrastructure.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Web.Areas.Admin.Controllers
{
    public class BooksController : AdminController
    {
        private readonly IAdminBookService bookService;
        private readonly IAdminAuthorService authorService;
        private readonly IAdminPublisherService publisherService;
        private readonly IAdminCategoryService categoryService;
        private readonly ICloudinaryService cloudinaryService;

        public BooksController(IAdminBookService bookService,
            IAdminAuthorService authorService,
            IAdminPublisherService publisherService,
            IAdminCategoryService categoryService,
            ICloudinaryService cloudinaryService)
        {
            this.bookService = bookService;
            this.authorService = authorService;
            this.publisherService = publisherService;
            this.categoryService = categoryService;
            this.cloudinaryService = cloudinaryService;
        }

        public async Task<IActionResult> Index()
        {
            var books = await this.bookService.GetAllBooks().ToListAsync();

            return this.View(books);
        }

        public async Task<IActionResult> Create()
        {
            return this.View(new BookInputModel()
            {
                Authors = await this.GetAuthorsAsync(),
                Publishers = await this.GetPublishersAsync()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Create(BookInputModel bookModel)
        {
            if (!this.ModelState.IsValid)
            {
                bookModel.Authors = await this.GetAuthorsAsync();
                bookModel.Publishers = await this.GetPublishersAsync();
                return this.View(bookModel);
            }
            string imageUrl = await this.cloudinaryService.UploadPictureAsync(
               bookModel.Image,
               bookModel.Title);

            var result = await this.bookService.CreateAsync(
                bookModel.Title,
                bookModel.AuthorId,
                bookModel.PublisherId,
                bookModel.Language,
                bookModel.Description,
                imageUrl,
                bookModel.CreatedOn.Value,
                bookModel.Price
                );

            if (result == false)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.BookNotCreated);
                return RedirectToAction(nameof(Index));
            }

            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Categories(int id)
        {
            var book = await this.bookService
               .GetByIdAsync<AdminBookListingServiceModel>(id);

            if (book == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.BookNotFound);
                return this.RedirectToAction(nameof(Index));
            }

            return this.View(new BookCategoriesViewModel
            {
                Book = book,
                BookCategories = book.Categories
                .Select(b => new SelectListItem
                {
                    Text = b.Name,
                    Value = b.Id.ToString()
                })
                .ToList(),
                AllCategories = await GetCategoriesAsync()
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddCategoryToBook(CategoryToBookInputModel model)
        {
            var book = await this.bookService.GetByIdAsync<AdminBookListingServiceModel>(model.BookId);
            if (book == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.BookNotFound);
                return this.RedirectToAction(nameof(Index));
            }

            var category = await this.categoryService.GetByIdAsync(model.CategoryId);

            if (category == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.CategoryNotFound);
                return this.RedirectToAction(nameof(Index));
            }

            var result =  await this.bookService.AddCategoryAsync(
                model.BookId,
                model.CategoryId);

            if (result == false)
            {
                this.TempData.AddErrorMessage(string.Format(
                    WebAdminConstants.CategoryAlreadyAddedToBook,
                     category.Name,
                     book.Title));

                return this.RedirectToAction(nameof(Categories), new { id = model.BookId });
            }

            this.TempData.AddSuccessMessage(string.Format(
                WebAdminConstants.CategoryAddedToBook,
                category.Name,
                book.Title));

            return this.RedirectToAction(nameof(Categories), new { id = model.BookId });
        }

        [HttpPost]
        public async Task<IActionResult> RemoveCategoryFromBook(CategoryToBookInputModel model)
        {
            var book = await this.bookService.GetByIdAsync<AdminBookListingServiceModel>(model.BookId);
            if (book == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.BookNotFound);
                return this.RedirectToAction(nameof(Index));
            }

            var category = await this.categoryService.GetByIdAsync(model.CategoryId);

            if (category == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.CategoryNotFound);
                return this.RedirectToAction(nameof(Index));
            }

             await this.bookService.RemoveCategoryAsync(
                model.BookId,
                model.CategoryId);

            this.TempData.AddSuccessMessage(string.Format(
                WebAdminConstants.CategoryRemovedFromBook,
                category.Name,
                book.Title));

            return this.RedirectToAction(nameof(Categories), new { id = model.BookId });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var book = await this.bookService
                .GetByIdAsync<AdminBookDetailsServiceModel>(id);

            if (book == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.BookNotFound);
                return RedirectToAction(nameof(Index));
            }

            return this.View(new BookInputModel
            {
               Title = book.Title,
               AuthorId = book.AuthorId,
               Authors = await GetAuthorsAsync(),
               PublisherId = book.PublisherId,
               Publishers = await GetPublishersAsync(),
               Language = book.Language,
               Description = book.Description,
               Image = book.Image,
               CreatedOn = book.CreatedOn,
               Price = book.Price
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, BookInputModel bookModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(bookModel);
            }
            string imageUrl = await this.cloudinaryService.UploadPictureAsync(
             bookModel.Image,
             bookModel.Title);

            var result = await this.bookService.EditAsync(
                id,
                  bookModel.Title,
                bookModel.AuthorId,
                bookModel.PublisherId,
                bookModel.Language,
                bookModel.Description,
                imageUrl,
                bookModel.CreatedOn.Value,
                bookModel.Price
                );

            if (result == false)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.BookNotEdited);
                return RedirectToAction(nameof(Index));
            }

            this.TempData.AddSuccessMessage(string.Format(
                WebAdminConstants.BookUpdated,
                bookModel.Title));

            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Hide(int id)
        {
            var book = await this.bookService
                .GetByIdAsync<AdminBookDetailsServiceModel>(id);

            if (book == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.BookNotFound);
                return RedirectToAction(nameof(Index));
            }

            await this.bookService.HideAsync(id);


            this.TempData.AddSuccessMessage(string.Format(
              WebAdminConstants.BookHidden,
              book.Title));

            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Show(int id)
        {
            var book = await this.bookService
             .GetByIdAsync<AdminBookDetailsServiceModel>(id);

            if (book == null)
            {
                this.TempData.AddErrorMessage(WebAdminConstants.BookNotFound);
                return RedirectToAction(nameof(Index));
            }

            await this.bookService.ShowAsync(id);

            this.TempData.AddSuccessMessage(string.Format(
              WebAdminConstants.BookShowed,
              book.Title));

            return this.RedirectToAction(nameof(Index));
        }

        private async Task<IEnumerable<SelectListItem>> GetAuthorsAsync()
        {
            var result = await this.authorService.GetAllActiveAuthors()
            .Select(a => new SelectListItem
            {
                Text = $"{a.FirstName} {a.LastName}",
                Value = a.Id.ToString()

BookStore/BookStore/Controllers/BooksController.cs
using BookStore.Controllers;
using BookStore.Services;
using BookStore.Web.Infrastructure.Extensions;
using BookStore.Web.Models.Reviews;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BookStore.Web.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly IBookService bookService;
        private readonly IReviewService reviewService;
        private readonly ICategoryService categoryService;

        public BooksController(IBookService bookService,IReviewService reviewService,ICategoryService categoryService)
        {
            this.bookService = bookService;
            this.reviewService = reviewService;
            this.categoryService = categoryService;
        }
        public async Task<IActionResult> Details(int id)
        {
            var book = await this.bookService.GetByIdAsync(id);

            if (book == null)
            {
                this.TempData.AddErrorMessage(WebConstants.BookNotFound);
                return this.RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var reviews = await reviewService.GetReviewsByBook(id).ToListAsync();
            book.Reviews = reviews;

            return this.View(book);
        }

        [HttpPost]
        public async Task<IActionResult> Review(ReviewInputModel reviewModel)
        {
            var creatorId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var result  = await this.reviewService.CreateAsync(reviewModel.BookId, reviewModel.Text, creatorId);

            if (result == false)
            {
                this.TempData.AddErrorMessage(WebConstants.ReviewNotCreated);
                return RedirectToAction(nameof(Details));
            }

            return this.RedirectToAction(nameof(Details), new { id = reviewModel.BookId });
        }
    }
}

BookStore/BookStore/Controllers/ShoppingCartController.cs
using BookStore.Services;
using BookStore.Web.Infrastructure.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BookStore.Web.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {

        private readonly IShoppingCartService shoppingCartservice;

        public ShoppingCartController(IShoppingCartService shoppingCartService)
        {
            this.shoppingCartservice = shoppingCartService;
        }
        public async Task<IActionResult> Index()
        {
            var userCartBooks = await this.shoppingCartservice.GetUserCartBooksAsync(this.User.Identity.Name);
            return View(userCartBooks);
        }

        public async Task<IActionResult> AddToShoppingCart(int id)
        {
            var result = await this.shoppingCartservice.AddBookToShoppingCartAsync(id, User.Identity.Name);
       
            if (result == false)
            {
                this.TempData.AddErrorMessage(WebConstants.BookExistInCart);
                return RedirectToAction(nameof(Index));
            }

            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> IncreaseQuantity(int id)
        {
            await this.shoppingCartservice.IncreaseQuantityAsync(id, User.Identity.Name);

            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DecreaseQuantity(int id)
        {
            await this.shoppingCartservice.DecreaseQuantityAsync(id, User.Identity.Name);

            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RemoveFromShoppingCart(int id)
        {
            var result  = await this.shoppingCartservice.RemoveBookFromShoppingCartAsync(id, User.Identity.Name);

            if (result == false)
            {
                this.TempData.AddErrorMessage(WebConstants.BookNotRemovedFromCart);
                return RedirectToAction(nameof(Index));
            }

            return this.RedirectToAction(nameof(Index));
        }
    }
}

BookStore/BookStore/Views/Books/Details.cshtml
@model BookDetailsServiceModel

@{
    ViewData["Title"] = "Детайли за книгата";
    List<CategoryBasicServiceModel> categories = Model.Categories.ToList();
}

<div class="row">
    <div class="col-md-4 mt-5 mb-4">
        <div class="book-page">
            <div class="d-flex justify-content-center">
                <img class="img-responsive" src=@Model.Image width="200" height="300">
            </div>
        </div>
    </div>
    <div class="col-md-6 mt-5 mb-3">
        <div class="justify-content-center w-50">
            <h4> @Model.Title</h4>
            <table class="table">
                <tbody>
                    <tr>
                        <td>Мнения: </td>
                        <td>@Model.ReviewsCount</td>
                    </tr>
                    <tr>
                        <td>Автор</td>
                        <td><a asp-controller="Home" asp-action="Index" asp-route-author=@Model.AuthorFullName class="text-info">@Model.AuthorFullName</a></td>
                    </tr>
                    <tr>
                        <td>Издателство</td>
                        <td><a asp-controller="Home" asp-action="Index" asp-route-publisher="@Model.PublisherName" class="text-info">@Model.PublisherName</a></td>
                    </tr>
                    <tr>
                        <td>Език</td>
                        <td>@Model.Language</td>
                    </tr>
                    <tr>
                        <td>Категории</td>
                        <td>
                            @for (int i = 0; i < categories.Count(); i++)
                            {
                                @if (i == categories.Count() - 1)
                                {
                                    <a asp-controller="Home" asp-action="Index" asp-route-CategoryId="@categories[i].Id" class="text-info">@categories[i].Name</a>
                                }
                                else
                                {
                                    <a asp-controller="Home" asp-action="Index" asp-route-CategoryId="@categories[i].Id" class="text-info">@categories[i].Name,</a>
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><a asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-id="@Model.Id" class="btn btn-primary btn-md"> Купи</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row mt-5">
    <div class=" col-md-7">
        <ul class="nav nav-tabs bg" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active text-dark" id="description-tab" data-toggle="tab" href="#home" role="tab" aria-controls="description" aria-selected="true">Описание</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" id="review-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="review" aria-selected="false">Мнения</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">@Model.Description</div>
            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">

                @if (Model.Reviews.Count() == 0)
                {
                    <p class="mt-3">Все още няма мнения за тази книга.</p>
                }
                <ul class="list-group mt-3 col-md-12">
                    @foreach (var review in Model.Reviews)
                    {
                        <li class="list-group-item mb-2">
                            <p class="font-italic"> от @review.CreatorUserName / дата: @review.CreatedOn.ToShortDateString()</p>
                            @review.Text
                        </li>
                    }
                </ul>
                <div class="mt-5 col-md-8">
                    <form asp-controller="Books" asp-action="Review" method="post">
                        <table style="position: relative; width: 100%;" cellspacing="1" cellpadding="4" border="0">
                            <tbody>
                                <tr>
                                    <td class="" align="right"><b>Мнение:</b></td>
                                    <td colspan="2" class="table-v2-cont-back" style="width: 90%;">
                                        <textarea name="Text" cols="30" rows="5" style="width: 100%;"></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="table-v2-title-back" valign="middle" height="46" align="center">
                                        <input name="" class="forms-buttons-submit-btn" type="submit" value="Добави">
                                        <input type="hidden" name="BookId" value="@Model.Id">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>